2020-06-29 19:24:25,684 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:24:42,568 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:24:57,013 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:28:36,267 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:29:15,965 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:30:02,999 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:30:47,342 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:37:25,666 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:37:25,710 ERROR: Unhandled exception [in ./app/tasks.py:48]
Traceback (most recent call last):
  File "./app/tasks.py", line 43, in process_files
    add_thisistest(folder_to_save, file)
  File "./app/processing.py", line 19, in add_thisistest
    output_stream = os.path.join(app.config['DOWNLOAD_FOLDER'], filename)
NameError: name 'app' is not defined
2020-06-29 19:38:30,184 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:38:30,208 ERROR: Unhandled exception [in ./app/tasks.py:48]
Traceback (most recent call last):
  File "./app/tasks.py", line 43, in process_files
    add_thisistest(folder_to_save, file)
  File "./app/processing.py", line 19, in add_thisistest
    output_stream = os.path.join(app.config['DOWNLOAD_FOLDER'], filename)
NameError: name 'app' is not defined
2020-06-29 19:39:01,595 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:39:01,620 ERROR: Unhandled exception [in ./app/tasks.py:48]
Traceback (most recent call last):
  File "./app/tasks.py", line 43, in process_files
    add_thisistest(folder_to_save, file)
  File "./app/processing.py", line 19, in add_thisistest
    output_stream = os.path.join(app.config['DOWNLOAD_FOLDER'], filename)
NameError: name 'app' is not defined
2020-06-29 19:41:48,070 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:41:48,133 ERROR: Unhandled exception [in ./app/tasks.py:49]
Traceback (most recent call last):
  File "./app/tasks.py", line 44, in process_files
    add_thisistest(folder_to_save, file)
  File "./app/processing.py", line 19, in add_thisistest
    output_stream = os.path.join(app.config['DOWNLOAD_FOLDER'], filename)
NameError: name 'app' is not defined
2020-06-29 19:43:24,806 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:43:38,468 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 19:43:51,362 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 20:16:58,482 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 20:31:09,851 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 21:09:33,996 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 21:16:06,841 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-29 23:35:44,146 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-29 23:41:26,506 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 00:02:53,185 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 10:39:40,472 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 10:42:23,766 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 10:42:52,276 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 10:44:38,109 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 10:49:46,424 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 10:50:01,982 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 10:50:17,250 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 10:50:30,051 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:03:47,575 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:04:12,668 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:32:50,662 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:32:50,694 ERROR: Unhandled exception [in ./app/tasks.py:48]
Traceback (most recent call last):
  File "./app/tasks.py", line 39, in process_files
    filenames = os.listdir(current_app.config['UPLOAD_FOLDER'])
NameError: name 'current_app' is not defined
2020-06-30 11:34:05,091 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:34:25,491 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:35:35,113 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:54:12,020 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:54:12,055 ERROR: Unhandled exception [in ./app/tasks.py:49]
Traceback (most recent call last):
  File "./app/tasks.py", line 42, in process_files
    output_stream = os.path.join(app.config['DOWNLOAD_FOLDER'], filename)
NameError: name 'filename' is not defined
2020-06-30 11:57:20,541 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 11:57:20,576 ERROR: Unhandled exception [in ./app/tasks.py:50]
Traceback (most recent call last):
  File "./app/tasks.py", line 43, in process_files
    output_stream = os.path.join(current_app.config['DOWNLOAD_FOLDER'], filename)
NameError: name 'filename' is not defined
2020-06-30 11:59:31,304 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 13:06:19,311 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 14:19:45,963 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 14:20:10,666 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 14:26:29,599 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 14:29:19,077 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 15:20:42,250 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 15:20:42,311 ERROR: Unhandled exception [in ./app/tasks.py:50]
Traceback (most recent call last):
  File "./app/tasks.py", line 40, in process_files
    filenames = os.listdir(current_app.config['UPLOAD_FOLDER'])
NameError: name 'current_app' is not defined
2020-06-30 15:21:31,879 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 15:21:31,942 ERROR: Unhandled exception [in ./app/tasks.py:50]
Traceback (most recent call last):
  File "./app/tasks.py", line 40, in process_files
    filenames = os.listdir(current_app.config['UPLOAD_FOLDER'])
NameError: name 'current_app' is not defined
2020-06-30 15:22:51,256 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 15:22:51,319 ERROR: Unhandled exception [in ./app/tasks.py:50]
Traceback (most recent call last):
  File "./app/tasks.py", line 40, in process_files
    filenames = os.listdir(current_app.config['UPLOAD_FOLDER'])
NameError: name 'current_app' is not defined
2020-06-30 15:26:04,868 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 15:26:04,912 ERROR: Unhandled exception [in ./app/tasks.py:50]
Traceback (most recent call last):
  File "./app/tasks.py", line 40, in process_files
    filenames = os.listdir(current_app.config['UPLOAD_FOLDER'])
NameError: name 'current_app' is not defined
2020-06-30 15:28:15,162 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 15:28:15,216 ERROR: Unhandled exception [in ./app/tasks.py:50]
Traceback (most recent call last):
  File "./app/tasks.py", line 40, in process_files
    filenames = os.listdir(current_app.config['UPLOAD_FOLDER'])
NameError: name 'current_app' is not defined
2020-06-30 15:28:55,426 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 15:33:52,876 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 16:10:08,879 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 16:13:40,719 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 16:15:28,612 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 16:41:06,671 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 16:55:15,087 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:02:21,063 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:09:57,162 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:13:10,581 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:21:51,132 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 17:33:14,132 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 17:33:36,325 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:34:17,348 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 17:34:24,403 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:35:22,351 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 17:35:26,250 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:35:54,908 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 17:35:58,308 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:36:25,674 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 17:37:06,094 INFO: Microblog startup [in /Users/elee/practice_app/microblog/app/__init__.py:86]
2020-06-30 17:37:17,502 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:37:32,066 INFO: Microblog startup [in ./app/__init__.py:86]
2020-06-30 17:38:54,115 INFO: Microblog startup [in ./app/__init__.py:86]
2020-07-01 11:56:07,031 INFO: Microblog startup [in /Users/elee/heroku_v5/microblog/app/__init__.py:86]
